### ISSUE TITLE
addon-knobs: Invalid prop `knob.value` of type `object` supplied to `ObjectType`, expected `string`

### ISSUE THREAD

**Issue by ranneyd** [storybooks/storybook#1292]
When putting an object in the `object` knob, I get the following error:

`Warning: Failed prop type: Invalid prop 'knob.value' of type 'object' supplied to 'ObjectType', expected 'string'.`

I think this is related to #1265

**Comment by shilman** [comment]
cc @Gongreg

**Comment by Gongreg** [comment]
@shilman, we just need to go through all proptypes, since they all can be wrong.

**Comment by skaraman** [comment]
similar issue here ->

 Invalid prop `knob.value` of type `number` supplied to `DateType`, expected `string`.

**Comment by SEAPUNK** [comment]
Getting the same, can't wrap my head around it:

```Warning: Failed prop type: Invalid prop `knob.value` of type `boolean` supplied to `BooleanType`, expected `string`.```

**Comment by Gongreg** [comment]
@shilman, Can someone go through all knobs and fix proptypes?

**Comment by shilman** [comment]
@Gongreg @SEAPUNK @ndelangen This is fixed but has not been released yet due to a broken build on this PR:

https://github.com/storybooks/storybook/pull/1303#issuecomment-309392511

Looking into it now.

**Comment by ndelangen** [comment]
Since we made a release in the mean time, I'm going to assume we can close this one.

This is kinda why I feel we should close issues as soon as merged..

**Comment by HugoMcPhee** [comment]
I think this still happens with numbers
_`Invalid prop 'knob.value' of type 'string' supplied to 'NumberType', expected 'number'.`_

when doing
`borderRadius:
            number("corners", 1, {
              min: 0,
              max: 3,
              step: 0.25,
              range: true
            })`
the slider only works when the value is a 0 string
``borderRadius:
            number("corners", "0", {
              min: 0,
              max: 3,
              step: 0.25,
              range: true
            })``
?
