### ISSUE TITLE
Still getting "accessing nonexistent addons channel"

### ISSUE THREAD

**Issue by jcreamer898** [storybooks/storybook#1981]
Even after bumping all my addons to the new version I'm still getting the non-existent addons error...

![](https://d.pr/i/brWGTD+)

Something I found a bit interesting is how NPM installed things. 

![](https://d.pr/i/3ItwKg+)

It's like `@storybook/react` has it's own version of addons?

**Comment by jcreamer898** [comment]
Ok, so the `node_modules/@storybook/addons` says it was imported by `knobs`...

![](http://d.pr/i/xkJnUb+)

And the one inside of the `node_modules/@storybook/react` says it was...

![](http://d.pr/i/IsWeIc+)

**Comment by jcreamer898** [comment]
BTW, I'm using npm `5.4.2`.

**Comment by shilman** [comment]
@jcreamer898 can you try removing your lock file and `node_modules` and reinstalling?

**Comment by jcreamer898** [comment]
Ahhh, I had removed `node_modules`, but never `package-lock`. Thanks!

**Comment by TheRohitSharma** [comment]
What do we do if removing package lock or yarn lock is not an option?

**Comment by Hypnosphi** [comment]
You can do the following:

1. Remove all the @storybook dependencies
2. Run `yarn` or `npm install` to update lockfile
3. Install @storybook dependencies back

**Comment by dennisnilsson** [comment]
Hi @jcreamer898 ! Im glad that you found out how to solve your issue. I'm sitting with the exact same thing when trying to use the addon "knobs". Could you describe your solution in more details, please? 

Did you just remove package-lock and then wrote npm install? Where did you find the package-lock file, I have 24 files with that name...

**Comment by Diokuz** [comment]
Very strange problem with versions mismatch. What the real problem behind this? Why addons cannot be written in a way where _patch_ (!!!) version doesn't matter?

**Comment by Hypnosphi** [comment]
@storybooks/team  I think we really need to make `@storybbok/addons` a peer dependency everywhere except the apps

**Comment by tmeasday** [comment]
If that helps! I think sadly the way npm is designed it is very hard to avoid this problem :/ I think the best solution is probably to figure out a way where addons do not need to depend on the addon package (i.e the API is passed to them by the user rather than them importing it). 

Perhaps a small improvement we could make is to make the addons package complain if it is installed more than once?

**Comment by Hypnosphi** [comment]
> figure out a way where addons do not need to depend on the addon package (i.e the API is passed to them by the user rather than them importing it).

That's an idea worth considering for #1209

**Comment by TroySchmidt** [comment]
I am testing with 3.3.0.alpha.3 and getting the non-existent channels message.  I am using TypeScript and there is no addons channel at all.  This behavior now is consistent across CI, locally, run, and build output.

**Comment by ndelangen** [comment]
@TroySchmidt First of all, thank you so much for giving the 3.3 alpha a go! 🙇 
It means a lot!

Second: sorry to hear it's not been a happy road, we will fix the problem!

**Comment by ndelangen** [comment]
https://github.com/storybooks/storybook/issues/269#issuecomment-346184773

**Comment by mjswensen** [comment]
It's also worth noting that you will also get this error if you haven't yet `register`ed your addon. Maybe that's super obvious to others, but it tripped me up for a while. 😊

**Comment by lewistaylor** [comment]
We have a setup using react-native that looks like this:

index.js
```
import Config from 'react-native-config';

import StorybookUI from './storybook';

import App from './main';

if (Config.RUN_STORYBOOK === '1') {
  module.exports = StorybookUI;
} else {
  module.exports = App;
}
```

We have no addons in the addons.js file, and every time we make a change running our app normally (so that hotreloading occurs), i.e. Config.RUN_STORYBOOK === '0', we get `Accessing not existent addons channel`.

We've managed to get around this by doing:

```
if (Config.RUN_STORYBOOK === '1') {
  configure(() => {
    require('./components/stories'); // eslint-disable-line global-require
  }, module);
  StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: true });
} else {
  StorybookUIRoot = <View />;
}
```

So that the storyboard import does not cause this issue. Is there a better way of initialising storybook so that importing it doesn't have the above effect? 

I realise this issue is closed but it does seem related

**Comment by elektronik2k5** [comment]
In case anyone still experiences this with the latest current version, `3.2.19`, I managed to solve it by upgrading to `3.4.0-alpha.5`. :confused:

**Comment by CoffiDev** [comment]
Hi, I'm experimenting this error.
![screen shot 2018-03-02 at 12 14 08 am](https://user-images.githubusercontent.com/6456756/36885819-d7a1d71c-1dae-11e8-8aec-c55dcb563c9c.png)

I have already read about this issue.

 I have already remove "node_modules package-lock.json" 

I tried using version 3.3.14 but it didn't work, so I tried using the last last version: 3.4.0-alpha.9



    "@storybook/addon-actions": "^v3.4.0-alpha.9",

    "@storybook/addon-notes": "^v3.4.0-alpha.9",

    "@storybook/addons": "^v3.4.0-alpha.9",

    "@storybook/channels": "^v3.4.0-alpha.9",

    "@storybook/vue": "^v3.4.0-alpha.9",


I have also manual check my package-lock.json and didn't find diferent versions of "storybook/addons"

I'm experiencing this issue when running "jest"

**Comment by elektronik2k5** [comment]
@CoffiDev, I've since successfully updated to `3.4.0-alpha.8`. npm `5.5.2`, node `8.9.2`. I'm using `@storybook/react` though.

**Comment by HazemEngMuh** [comment]
I cannot solve this error "accessing nonexistent addons channel"

"@storybook/addon-actions": "3.3.11",
    "@storybook/addons": "3.3.11",
    "@storybook/react": "3.3.11",
    "react-autocomplete": "1.7.2",
    "react-beautiful-dnd": "4.0.1",
    "storybook": "1.0.0",
    "styled-components": "3.0.2"
Is there any  one have stable version ??

**Comment by igor-dv** [comment]
> "storybook": "1.0.0",

what is this ?

**Comment by HazemEngMuh** [comment]
when i try to solve it I added it now I remove it but not  works

**Comment by igor-dv** [comment]
Do you have a lock file?

**Comment by HazemEngMuh** [comment]
yes I have. When I make any change I delete it and make npm i from new

**Comment by igor-dv** [comment]
🤔 any public repo where we can reproduce the problem?

**Comment by HazemEngMuh** [comment]
Two minutes will be ready

**Comment by HazemEngMuh** [comment]
https://github.com/HazemEngMuh/ReactDNDExample

**Comment by igor-dv** [comment]
I don't see any storybook related code there

**Comment by HazemEngMuh** [comment]
https://github.com/HazemEngMuh/ReactDNDExample/blob/master/src/board/board.jsx
Third row

**Comment by igor-dv** [comment]
That's not how you should use addons and Storybook in particular. 
Please refer to the [documentation](https://storybook.js.org/basics/introduction/)

**Comment by SEAPUNK** [comment]
Wait, so I'm confused: Has the addons as peerDependency issue been solved? We've been continuously been getting bitten by this issue, especially since we have a policy of pinning our dependencies (installed addons @ 3.3.14, but 3.3.15 exists, so yarn installs 3.3.14 to node_modules and 3.3.15 to storybooks/react/node_modules).

Looking in @storybooks/react, it's still listing it as a dependency -- if you expect the user to only have one copy, it should be a peerDependency where the user installs it on their side (a la react and react-dom).

**Comment by danielduan** [comment]
@SEAPUNK Your `@storybook/react` should be the only thing installing a copy of `@storybook/addons`.

You don't need to install addons yourself. It might trigger a missing peer dependency warning, but you should be fine.

**Comment by Hypnosphi** [comment]
> @storybooks/react, it's still listing it as a dependency

That's the thing we have to change in 4.0

**Comment by SEAPUNK** [comment]
@danielduan That's magical, relies wholly on the hoisting system, and I don't like it. I strongly believe it should be the other way around. I'll wait until 4.0, I guess.

And we do explicitly use the dependency in some of our code, e.g. registering a custom addon

**Comment by gvaldambrini** [comment]
I'm having this problem as well. In my case, I have my Storybook addon which depends (using `peerDependencies` and `devDependencies`) by `@storybook/addons` and `@storybook/addon-actions`.  The addon is a package part of a lerna repository, and in the same repo I have an example package which uses the addon. The example package lists `@storybook/addons` and `@storybook/addon-actions` as `dependencies`. The packages lock down both the dependencies to the `3.3.15` version, however, if I run the examples using storybook and I perform any action which triggers the `action addon`, the problem arises. 

To reproduce the problem, [clone the repository](https://github.com/gvaldambrini/storybook-router/tree/split-packages), switch branch to `split-packages`, then after `yarn install && yarn bootstrap` run `yarn storybook-react-examples` and as soon as the page is loaded, click the `Home` link. 
Any idea how to solve this? Thanks!

**Comment by SEAPUNK** [comment]
Try inspecting your dependency tree with `yarn why` to figure out if there are multiple addon packages installed:

```
yarn why @storybook/addons
```

**Comment by gvaldambrini** [comment]
The problem is that in my case it is correct (as far as I understand) that both the package and the example have `@storybook/addons` installed. I managed to workaround the problem using lerna hoisting so that they share the same instance of `@storybook/addons`, but of course it's a workaround and not the ideal solution. 
I hope that in the next storybook version the issue will be fixed as reported by @Hypnosphi. Thanks anyway!

**Comment by Hypnosphi** [comment]
I think we should enforce channel being a singleton using some global variable like `window.__STORYBOOK_CHANNEL` instead of relying on a single package instance

**Comment by Hypnosphi** [comment]
Fix released as [`4.0.0-alpha.2`](https://github.com/storybooks/storybook/releases/tag/v4.0.0-alpha.2)

**Comment by pebie** [comment]
For those who still get this issue, I just figured out that I use babel module resolver.
My plugins config in `.babelrc` was : 

```javascript
...
"plugins": [
    ["module-resolver", {
      "root": ["src/app", ".storybook"],
    }]
  ]
...
```

Then I decided to move `.storybook` in a `storybook` env : 
```javascript
...
"env": {
    "storybook": {
      "plugins":[
          ["module-resolver",{
           "root": [".storybook"],
        }]
       ]
    },
  },
"plugins": [
    ["module-resolver", {
      "root": ["src/app"],
    }]
  ]
}
"plugins": [
    ["module-resolver", {
      "root": ["src/app", ".storybook"],
    }]
  ]
...
`

It's obvious but, just in case, verify if you don't load any storyboard files when you run your app

Hope this can help.

**Comment by g-verma** [comment]
if still you are facing the issue try this showAddonPanel: false, in config.js

**Comment by fahidnasir** [comment]
Fixed by Removing `node_modules` folder and re-installing the packages.
