### ISSUE TITLE
[3.3.3] eslint: Unable to resolve path to module @storybook/react

### ISSUE THREAD

**Issue by DimaRGB** [storybooks/storybook#2602]
### Issue details

After update to `3.3.3` see eslint error: `Unable to resolve path to module @storybook/react. (import/no-unresolved)`

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react 3.3.3`

### Screenshots / Screencast / Code Snippets (Optional)

```js
import * as storybook from '@storybook/react';
```

eslintrc.js:
```js
  ...
  parserOptions: {
    ecmaVersion: 8,
    sourceType: 'module',
    ecmaFeatures: {
      impliedStrict: true,
      jsx: true,
    },
  },
  ...
```

**Comment by Hypnosphi** [comment]
Probably related to adding `jsnext:main` in #2589

**Comment by DimaRGB** [comment]
seems like eslint try to use `jsnext:main` but `src` folder not published.

**Comment by alansouzati** [comment]
hey, great that we have a merged PR for this! :) Any news when we will have it released? also, I believe this issue can be closed?

**Comment by Hypnosphi** [comment]
@shilman how about a patch release?

**Comment by Hypnosphi** [comment]
Fix released as [`3.3.4`](https://github.com/storybooks/storybook/releases/tag/v3.3.4)

**Comment by hswolff** [comment]
Sadly I'm still seeing this issue. 

The PR only removed `src` from the root `.npmignore` and not from the individual package itself: https://github.com/storybooks/storybook/blob/master/app/react/.npmignore#L2

I believe we need to remove that from the individual package to have the `src` directory published as well.

**Comment by Hypnosphi** [comment]
Oh I see

**Comment by hswolff** [comment]
Incoming!

**Comment by hswolff** [comment]
PR: https://github.com/storybooks/storybook/pull/2677

**Comment by csi-lk** [comment]
Hmm if I manually remove `src` from the `.npmignore` in the @storybook/react folder I still get this eslint error, it could be i'm misunderstanding the solution?

**Comment by hswolff** [comment]
You mean in your `node_modules` folder in your application? I'm guessing that it's because the `jsnext:main` value points to a file that doesn't exist. Perhaps try copying over the `src/` folder from this repo into your node_modules folder, which should fix the issue. May be good to do that to verify. That's what my PR will change when a new npm package is published.

**Comment by csi-lk** [comment]
I ended up giving up and reverting, will just wait for this change to come through, cheers
