### ISSUE TITLE
warning：Throttling history state changes to prevent the browser from hanging.

### ISSUE THREAD

**Issue by shywei** [storybooks/storybook#4033]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I meet this warning when click the sidemenu to view a story. 
I make a breakpoint to the code where throws this warning. It seems that that line is called many times after click the sidemenu. 
Is this a bug of storybook or a problem with my usage?

Is this the same problem as #3211 

### Steps to reproduce

click the sidebar to view a story

### Please specify which version of Storybook and optionally any affected addons that you're running

    "@storybook/addon-actions": "^3.4.3",
    "@storybook/addon-centered": "^3.4.2",
    "@storybook/addon-knobs": "^3.4.2",
    "@storybook/addon-links": "^3.4.2",
    "@storybook/addon-options": "^3.4.2",
    "@storybook/vue": "^3.4.2",

### Affected platforms 

Google Chrome 68.0.3440.106

### Screenshots / Screencast / Code Snippets (Optional)
![warning](https://user-images.githubusercontent.com/8448168/44257937-26f50a80-a240-11e8-8f0b-d02e589d69d5.png)

**Comment by mattjennings** [comment]
I seem to run into this after a hot reload and then clicking on a new story. Removing the knobs addon fixes it. I'm on v3.4.10.

Looks like it's the same thing as #3211 and fixed in v4, but I haven't tried it yet.

**Comment by Abdisalan** [comment]
I ran into this as well.. happens to me when there are a lot of knobs on a single component

**Comment by rodneyrehm** [comment]
> Should be much much better in 4.0.0

I still experience this with `@storybook/vue` and `@storybook/addon-knobs` in version 4.0.4.

There's a text field and I type (not paste) `hello world` (in a reasonable speed), I end up with the knobs input showing "hel d" and the browser console showing 98x `Throttling history state changes to prevent the browser from hanging.`.

The problem can be reproduced with a very simple setup:

```js

import { storiesOf } from '@storybook/vue'
import { text } from '@storybook/addon-knobs'

storiesOf('Knobs Performance Demo', module).add('simple input', () => {
  return {
    template: `<input type="text" :value="value" />`,
    data () {
      return {
        value: text('input.value', ''),
      }
    },
  }
})
```

here's the trace I'm getting for one of those messages:

```
handle_routing.js:64 Throttling history state changes to prevent the browser from hanging.
  | changeUrl | @ | handle_routing.js:64
  | (anonymous) | @ | handle_routing.js:129
  | (anonymous) | @ | index.js:41
  | fireSubscriptions | @ | index.js:40
  | update | @ | index.js:78
  | setOptions | @ | api.js:135
  | setOptions | @ | init_api.js:45
  | (anonymous) | @ | index.js:21
  | (anonymous) | @ | index.js:160
  | _handleEvent | @ | index.js:159
  | (anonymous) | @ | index.js:35
  | _handleEvent | @ | index.js:116
  | postMessage (async) |   |  
  | send | @ | index.js:74
  | handler | @ | index.js:71
  | emit | @ | index.js:80
  | emitOptions | @ | index.js:51
  | wrapper | @ | index.js:71
  | (anonymous) | @ | make-decorator.js:42
  | (anonymous) | @ | make-decorator.js:66
  | (anonymous) | @ | index.js:32
  | story | @ | index.js:29
  | (anonymous) | @ | index.js:41
  | story | @ | index.js:29
  | wrapper | @ | index.js:53
  | (anonymous) | @ | make-decorator.js:42
  | (anonymous) | @ | make-decorator.js:66
  | (anonymous) | @ | index.js:32
  | story | @ | index.js:29
  | withSubscriptionTracking | @ | client_api.js:58
  | (anonymous) | @ | index.js:32
  | (anonymous) | @ | story_store.js:162
  | render | @ | render.js:41
  | renderMain | @ | start.js:190
  | renderUI | @ | start.js:210
  | forceReRender | @ | start.js:220
  | (anonymous) | @ | index.js:160
  | _handleEvent | @ | index.js:159
  | handler | @ | index.js:74
  | emit | @ | index.js:80
  | forceReRender | @ | registerKnobs.js:22
  | knobChanged | @ | registerKnobs.js:43
  | (anonymous) | @ | index.js:160
  | _handleEvent | @ | index.js:159
  | (anonymous) | @ | index.js:35
  | _handleEvent | @ | index.js:116
  | postMessage (async) |   |  
  | send | @ | index.js:74
  | handler | @ | index.js:71
  | emit | @ | index.js:80
  | (anonymous) | @ | Panel.js:134
  | (anonymous) | @ | Panel.js:145
  | (anonymous) | @ | PropForm.js:65
  | (anonymous) | @ | Text.js:50
  | TextareaAutosize._this._onChange | @ | react-textarea-autos….esm.browser.js:246
  | callCallback | @ | react-dom.development.js:149
  | invokeGuardedCallbackDev | @ | react-dom.development.js:199
  | invokeGuardedCallback | @ | react-dom.development.js:256
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:270
  | executeDispatch | @ | react-dom.development.js:561
  | executeDispatchesInOrder | @ | react-dom.development.js:583
  | executeDispatchesAndRelease | @ | react-dom.development.js:680
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.development.js:688
  | forEachAccumulated | @ | react-dom.development.js:660
  | runEventsInBatch | @ | react-dom.development.js:816
  | runExtractedEventsInBatch | @ | react-dom.development.js:824
  | handleTopLevel | @ | react-dom.development.js:4820
  | batchedUpdates$1 | @ | react-dom.development.js:18918
  | batchedUpdates | @ | react-dom.development.js:2150
  | dispatchEvent | @ | react-dom.development.js:4899
  | interactiveUpdates$1 | @ | react-dom.development.js:18973
  | interactiveUpdates | @ | react-dom.development.js:2169
  | dispatchInteractiveEvent | @ | react-dom.development.js:4876
```
