### ISSUE TITLE
addon-info show Unknown component names

### ISSUE THREAD

**Issue by feonit** [storybooks/storybook#4881]
**Describe the bug**
When i run build-storybook after upgrade from 4.0.8 to 4.1.0-alpha.8 addon-info show me in Story Source section code like this:
```js
<Unknown>
  <Unknown>
    <Text>
      Enter
    </Text>
  </Unknown>
</Unknown>
```

**Expected behavior**
before upgrade code was like below
```js
<Background>
  <Button>
    <Text>
      Enter
    </Text>
  </Button>
</Background>
```
and i use custom .storybook/.babelrc file with
```js
   plugin:  "add-react-displayname"
```
**System:**
    "@storybook/addon-info": "4.1.0-alpha.8",
    "@storybook/addon-knobs": "4.1.0-alpha.8",
    "@storybook/addon-options": "4.1.0-alpha.8",
    "@storybook/cli": "4.1.0-alpha.8",
    "@storybook/react": "4.1.0-alpha.8",
    "react-scripts": "2.1.1",

![2018-11-28 17 01 43](https://user-images.githubusercontent.com/3956831/49157021-e1140c00-f32f-11e8-97e4-9c4197365feb.png)

**Comment by igor-dv** [comment]
Please check later versions of Storybook, it was already fixed.

**Comment by irvingv8** [comment]
I'm still able to reproduce this with version 5.0.3

**Comment by maeligg** [comment]
I also still have the issue on V5.0.3, but only on some components. I wasn't able to identify a common pattern between them so far.

**Comment by irvingv8** [comment]
I just noticed that the issue arises when u define your components something like:

``` export default () => {} ```

but if you something like:
```const NamedComponent = () => {}
export default NamedComponent```

it gets fixed

**Comment by maeligg** [comment]
@irvingv8 indeed, this fixed it for me too.
