### ISSUE TITLE
Angular - Stories redeclaring components in DynamicModule

### ISSUE THREAD

**Issue by Raidok** [storybooks/storybook#5542]
**Is your feature request related to a problem? Please describe.**
I am building a component library, which contains primitive (independent) components as well as components that are a composition of other primitive and/or complex components. For simplicity's sake I have a module for every exported component where I can define all nested components(modules) that it depends on.

When writing a story for such a component I expected this would work:

```
storiesOf('Button', module)
  .addDecorator(withKnobs)
  .addDecorator(
    moduleMetadata({
      imports: [ButtonModule],
    })
  )
  .add('default', () => ({
    component: ButtonComponent,
    props: {
      disabled: boolean('disabled', false)
    }
  }));
```

But this leads to the following error:

> Promise rejection: Type ButtonComponent is part of the declarations of 2 modules: ButtonModule and DynamicModule! Please consider moving ButtonComponent to a higher module that imports ButtonModule and DynamicModule.

I have traced down that it comes from [helpers.ts](https://github.com/storybooks/storybook/blob/next/app/angular/src/client/preview/angular/helpers.ts#L54) where it always creates a DynamicModule in which it declares the component mentioned in the story.

If I define the component in the story with `template` (instead of `component`) it works fine but the downside is that I have to manually mention all the props/bindings for knobs in the template.

```
  .add('default', () => ({
    template: '<my-button [disabled]="disabled">',
    props: {
      disabled: boolean('disabled', false)
    }
  }));
```

**Describe the solution you'd like**
When writing stories for a component I would like to import the NgModule in which the component is declared using moduleMetadata decorator and use the components reference (not template) in stories together with props/bindings.

**Describe alternatives you've considered**
1. Using the template, letting Storybook wrap a component around my component - it's tedious to mention the bindings in the HTML string.
2. Changed `helpers.ts` to NOT include my component in DynamicModule's declarations - breaks the bindings altogether.

**Are you able to assist bring the feature to reality?**
I have described what I have considered but I doubt I could provide an elegant solution to it.

**Comment by tmeasday** [comment]
Hi @Raidok, we are always keen for more people to help out, especially with Angular!

**Comment by pascaliske** [comment]
Hi @Raidok,

I run into the same issue as you but I have just a single NgModule declaring all my components. I tested the second of your alternatives and removed the `AnnotatedComponent` from the declarations in [/app/angular/src/client/preview/angular/helpers.ts#L63](https://github.com/storybooks/storybook/blob/master/app/angular/src/client/preview/angular/helpers.ts#L63) and it worked for me.

Can't say if this would be a decent fix for this as it would imply that users need to import a NgModule declaring their component for a story. I think it would be better to "check" if the component should be added dynamically to the declares array...

I will try to find a way to do this if I find the time to debug this a little further. 🙂

**Comment by MaximSagan** [comment]
I agree with Raidok. Ideally, we should be able to import the module that a component was originally declared in (so that any of its dependent child components are also declared) and specify its props using Typescript without template binding.

**Comment by KamiShikkaku** [comment]
I have created a PR (#6346) for this. As has been discussed, the issue is that when Storybook sees a component specified in the form `component: MyComponent` it assumes that the component requires declaration, and hence we get the "MyComponent is part of the declarations of 2 modules" when it's already been declared in an imported module (generally its feature module).

To solve this, I simply added an boolean option to the story object (the object where the component, props etc. are specified) called "requiresComponentDeclaration" which defaults to true (non-breaking change) but would be set to false in the situation that we're describing.

You can check out the working example in my PR [here](https://monorepo-git-fork-maximsagan-angular-dont.storybook.now.sh/examples/angular-cli/?path=/story/custom-feature-module-as-context--component-with-self-and-dependencies-declared-in-its-feature-module).

Note: As @pascaliske alluded to, ideally we would check imported modules (and those modules' imported modules recursively) to see if the component has been declared in one of them and then only declare the component of it hasn't been, but I'm not sure if that's possible with the APIs available to us.

**Comment by MaximSagan** [comment]
I have created a PR (#6346) for this. As has been discussed, the issue is that when Storybook sees a component specified in the form "component: MyComponent" it assumes that the component requires declaration, and hence we get the "MyComponent is part of the declarations of 2 modules" when it's already been declared in an imported module (generally it's feature module).

To solve this, I simply added a boolean option to the "story" object (the object where the component, props etc. are specified) called "requiresComponentDeclaration" which defaults to true (non-breaking change) but would be set to false in the situation that we're describing.

You can check out the working example in my PR [here](https://monorepo-git-fork-maximsagan-angular-dont.storybook.now.sh/examples/angular-cli/?path=/story/custom-feature-module-as-context--component-with-self-and-dependencies-declared-in-its-feature-module).

Note: As @pascaliske alluded to, ideally we would check imported modules (and those modules' imported modules recursively) to see if the component has been declared in one of them and then only declare the component of it hasn't been, but I'm not sure if that's possible with the APIs available to us.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.36 containing PR #6346 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.40 containing PR #6666 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by jaydeep987** [comment]
> I have created a PR (#6346) for this. As has been discussed, the issue is that when Storybook sees a component specified in the form "component: MyComponent" it assumes that the component requires declaration, and hence we get the "MyComponent is part of the declarations of 2 modules" when it's already been declared in an imported module (generally it's feature module).
> 
> To solve this, I simply added a boolean option to the "story" object (the object where the component, props etc. are specified) called "requiresComponentDeclaration" which defaults to true (non-breaking change) but would be set to false in the situation that we're describing.
> 
> You can check out the working example in my PR [here](https://monorepo-git-fork-maximsagan-angular-dont.storybook.now.sh/examples/angular-cli/?path=/story/custom-feature-module-as-context--component-with-self-and-dependencies-declared-in-its-feature-module).
> 
> Note: As @pascaliske alluded to, ideally we would check imported modules (and those modules' imported modules recursively) to see if the component has been declared in one of them and then only declare the component of it hasn't been, but I'm not sure if that's possible with the APIs available to us.

I don't think this is still working, at least in my case.
I am using `@storybook/angular@5.2.6`. 

```
return {
        component,
        moduleMetadata: getModuleMetadata(),
        requiresComponentDeclaration: false,
      };
```

**Comment by fbaba-nibtravel** [comment]
Hi, I've upgraded to v6.0.21 and it seems this issue is back. Is anyone else having this problem again?

**Comment by hankchiutw** [comment]
I'm using @storybook/angular 6.1.10 and having the same error after hot reloading.
Everything is ok at the first load.

**Comment by shilman** [comment]
@storybookjs/angular is this a regression? ☝️

**Comment by vlachnerQ6** [comment]
Using @storybook/angular": "^6.1.15
Do I have to use the legacy API for the `requiresComponentDeclaration` to work?

**Comment by shilman** [comment]
cc @ThibaudAV

**Comment by ThibaudAV** [comment]
On 5.1 the option `requiresComponentDeclaration` has been added and then quickly removed 🤣 

added in v5.1.0-alpha.36 containing PR https://github.com/storybookjs/storybook/pull/6346
removed in v5.1.0-alpha.40 containing PR https://github.com/storybookjs/storybook/pull/6666 😈 

if I don't make a mistake :
This problem means that storybook cannot detect that the component is already declared in an angular module imported by the story (see `getExistenceOfComponentInModules` function)

In any case that I have tested the `getExistenceOfComponentInModules` does the job correctly. To be able to identify the problematic case it would be necessary to have a way to reproduce it.
can you give us a test repository with the error ?

**Comment by MickL** [comment]
@ThibaudAV Where do you see `getExistenceOfComponentInModules`?

**Comment by ThibaudAV** [comment]
Legacy one is [here](https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/angular/helpers.ts#L106) in next branche

The new one used in last storybook version (6.2) is [here](https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/angular-beta/utils/NgModulesAnalyzer.ts#L8)  (with new name `isComponentAlreadyDeclaredInModules`)
And some test [here](https://github.com/storybookjs/storybook/blob/next/app/angular/src/client/preview/angular-beta/utils/NgModulesAnalyzer.test.ts)

**Comment by criskrzysiu** [comment]
@ThibaudAV  I think this feature (isComponentAlreadyDeclaredInModules) stopped working again in 6.3+ :(

**Comment by fasidOnGit** [comment]
I using `@storybook/angular: ^6.5.0-alpha.42`. this issue is back. any help ?
