### ISSUE TITLE
Changing stories should reset iframe scroll position to top

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5598]
**Describe the bug**
When a user changes stories the iframe scroll position is not reset. If you scroll halfway down a page and change the story you will still be at the same scroll position in the new story. 

**To Reproduce**
1. Go to the [AboutScreen:new version required](http://localhost:9011/?path=/story/ui-settings-aboutscreen--new-version-required) in the official storybook. 
2. Adjust the addon pane position so a scroll bar appears
3. Scroll down to the bottom of the iframe
4. Switch to [AboutScreen:up to date](http://localhost:9011/?path=/story/ui-settings-aboutscreen--up-to-date). 
5. Notice that the scroll position does not reset

**Expected behavior**
The scroll position should reset to top every time you change a story

**Screenshots**
An lossy Gif:
![screen recording 2019-02-14 at 07 57 pm](https://user-images.githubusercontent.com/263385/52827442-d6495780-3092-11e9-990a-cc62ef18c1fb.gif)

**Comment by tmeasday** [comment]
This has something to do with emotion. I don't quite know the mechanism, but it can be reproduced pretty easily with the following story:

```
const Div = styled.div``;

export story = () => (
  <>
    <div style={{ height: '1000px' }} />
    <Div>foobar</Div>
  </>
);
```

Try opening the story in its own iframe and commenting the `<Div>` in and out. I see this when it is there:

<img width="153" alt="image" src="https://user-images.githubusercontent.com/132554/52924444-faea4b80-3380-11e9-8295-f1e82778a069.png">

(notice how "foobar" is scrolled into view for no apparent reason)

**Comment by tmeasday** [comment]
Any ideas @ndelangen?

**Comment by ndelangen** [comment]
Not an emotion thing, AFAIT:

There's no difference in behavior between these:

```jsx
import React from 'react';
import { styled } from '@storybook/theming';

const Div = styled.div({});

export default {
  title: 'Core|Scroll',
  decorators: [
    fn => (
      <div>
        <div style={{ height: '100vh' }} />
        <div>{fn()}</div>
      </div>
    ),
  ],
};

export const story1 = () => <pre>story 1</pre>;
story1.title = 'story with 100vh padding 1';

export const story2 = () => <pre>story 2</pre>;
story2.title = 'story with 100vh padding 2';
```

```jsx
import React from 'react';
import { styled } from '@storybook/theming';

const Div = styled.div({});

export default {
  title: 'Core|Scroll',
  decorators: [
    fn => (
      <div>
        <div style={{ height: '100vh' }} />
        <Div>{fn()}</Div>
      </div>
    ),
  ],
};

export const story1 = () => <pre>story 1</pre>;
story1.title = 'story with 100vh padding 1';

export const story2 = () => <pre>story 2</pre>;
story2.title = 'story with 100vh padding 2';
```

**Comment by ndelangen** [comment]
Can confirm it's in firefox too, not some random browser bug

**Comment by tmeasday** [comment]
OK, that's weird. My bad, it was not emotion. Following on from your example though, this does not scroll:

```
import React from 'react';
import { styled } from '@storybook/theming';

const Div = styled.div({});

export default {
  title: 'Core|Scroll',
  decorators: [
    fn => (
      <div>
        <div style={{ height: '100vh' }} />
        <Div>{fn()}</Div>
      </div>
    ),
  ],
};

export const story1 = () => <pre>story 1</pre>;
story1.title = 'story with 100vh padding 1';

export const story2 = () => <pre>story 2</pre>;
story2.title = 'story with 100vh padding 2';
```

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.5 containing PR #5713 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by LuigiRamosWeb** [comment]
I'm afraid the exact behavior described in #1 is still happening in version 6.5.6

**Comment by lazysergey** [comment]
latest 6.5.13 still has the same

**Comment by gzusgo-thinkbig** [comment]
This behavior is still presents on V7 too.
