### ISSUE TITLE
Info addon doesn't inherit styling

### ISSUE THREAD

**Issue by B3zo0** [storybooks/storybook#5723]
**Describe the bug**
In v4 the info inherited the base font-family and stylings. In v5 it does not.

**To Reproduce**
Use info addon.

**Expected behavior**
I expect the behavior from v4 where the font-family is the same as in the outer panels.

**Screenshots**
**v5**
![v5](https://content.screencast.com/users/Bezoo/folders/Jing/media/a06051dc-7993-4feb-87dd-c497ba973cee/2019-02-22_1612.png)

**v4**
![v4](https://content.screencast.com/users/Bezoo/folders/Jing/media/e9c6bd8b-66e6-444f-b2d8-ebced235dc4c/2019-02-22_1613.png)

**System:**
 - Addons: Info
 - Version: 5.0.0-rc.4

**Comment by shilman** [comment]
@B3zo0 Thanks for the report. Bugfix PRs are welcome for this!

**Comment by mateoholman** [comment]
@shilman I'll take a crack at this one if no one else is working on it.

**Comment by shilman** [comment]
Awesome @mateoholman, thanks for taking this on! Our storybook dev setup is documented here https://github.com/storybooks/storybook/blob/next/CONTRIBUTING.md#development-guide and feel free to get help here or on our Storybook Discord/Slack if you run into issues. 🙇

**Comment by B3zo0** [comment]
I was able to workaround this with this code in config.js:
```js
addDecorator(storyFn => (
  <ThemeProvider theme={themes.normal}>
    <Global styles={createReset} />
    {storyFn()}
  </ThemeProvider>
))
```

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.8 containing PR #5759 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by mfellner** [comment]
Unfortunately this appears to be still an issue in the current version 5.0.0. 😕

**Comment by SteffenGorenflo** [comment]
I experience the same issue. I found that if the info is rendered with the options: `{info: {inline: false}}` the styles get applied:
![image](https://user-images.githubusercontent.com/5612074/54445383-f0835d80-4744-11e9-8feb-ef9e2810d5e6.png)

But the problem persists when rendering the info inline

**Comment by SteffenGorenflo** [comment]
I think, I found the commit responsible for this issue: https://github.com/storybooks/storybook/pull/5444/commits/c7f624e54afa50622b4b45313ede89f9571f65b2#diff-36f288162c3cc9bd518d680f366bbe54L54

You can add the font family to that `.infoBody` css class just like in https://github.com/storybooks/storybook/pull/5759/files but I don't know if thats the right way, since you may have some global styling/theming/fonts system which should be used?!

**Comment by tomspeak** [comment]
Facing the same issue, when passing in a custom `styles` object that is mapped from https://github.com/storybooks/storybook/blob/master/addons/info/src/components/Story.js#L19. - some, but not all styles are applied.

Notably, I am trying to apply `display: none` to a lot of the styles to reduce noise.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 containing PR #6186 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.4 containing PR #6186 that references this issue. Upgrade today to try it out!
