### ISSUE TITLE
Syntax highlighted code blocks render as gray on gray for unsupported languages in dark theme

### ISSUE THREAD

**Issue by stof** [storybooks/storybook#6797]
**Describe the bug**

**To Reproduce**
1. Create a markdown note for a story
2. Put a code block in it using a language for which highlighting is not loaded in storybook (I used ```` ```twig ```` when discovering the bug)
3. use the dark theme for your storybook
4. go to the notes panel to see these notes

**Expected behavior**
The code block is readable (as happens in light themes).

**Screenshots**
![storybook_bug_dark](https://user-images.githubusercontent.com/439401/57846868-723f4800-77d5-11e9-8c69-e94b0dc3ca62.png)
![storybook_bug_light](https://user-images.githubusercontent.com/439401/57846869-72d7de80-77d5-11e9-8025-972c08e66ba8.png)

**Code snippets**
````md
This component is not meant to be rendered manually, but using Pagerfanta:

```twig
<div class="text-center spacer-outer-top-tiny">
    {{ pagerfanta(members, 'material') }}
</div>
```
````

**System:**
 - OS: Ubuntu 18.04
 - Browser: firefox
 - Framework: html (but irrelevant here)
 - Addons: notes
 - Version: 5.0.11

**Additional context**
Note that disabling syntax highlighting (by removing the language on the codeblock) makes the text readable (but we miss the copy option then).

**Comment by stof** [comment]
On a side note, I would be interested in getting an answer on https://github.com/storybooks/storybook/issues/6144 as well (because this codeblock would be even better with proper highlighting.

**Comment by ndelangen** [comment]
I'll see what I can do

**Comment by shilman** [comment]
@ndelangen you might want to check out the changes @domyen made in the `release/docs-technical-preview` branch. We have nice syntax highlighting for the Source block in both light & dark modes.

**Comment by ndelangen** [comment]
@stof Would you like to review my PR?

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-rc.0 containing PR #6814 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by ChazUK** [comment]
@shilman I know this is a long closed ticket, but I'm trying to pass `language="scss"` to the `<Source />` block in `@storybook/addon-docs` with version 6.3.0 and I'm still getting an unhighlighted grey block. Is there something I am missing to add support for more languages?

**Comment by ChazUK** [comment]
Ignore me! Found it here https://storybook.js.org/docs/react/writing-docs/mdx#syntax-highlighting
