### ISSUE TITLE
5.1.0-rc.0 does not start: Error parsing babel config file

### ISSUE THREAD

**Issue by kaiyoma** [storybooks/storybook#6864]
**Describe the bug**
After upgrading from 5.1.0-alpha.39 to 5.1.0-rc.0, Storybook does not start. It appears to be parsing a JavaScript file with a JSON parser.

**Code snippets**
Here's the shell output:

```
$ start-storybook -p 9001 -c storybook
info @storybook/react v5.1.0-rc.0
info
info => Loading presets
info => Loading presets
ERR! => Error parsing babel config file: JSON5: invalid character 'c' at 1:1
ERR! => Error parsing babel config file: JSON5: invalid character 'c' at 1:1

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

ERR! SyntaxError: JSON5: invalid character 'c' at 1:1
ERR!     at syntaxError (...\node_modules\json5\lib\parse.js:1083:17)
ERR!     at invalidChar (...\node_modules\json5\lib\parse.js:1028:12)
ERR!     at Object.value (...\node_modules\json5\lib\parse.js:287:15)
ERR!     at lex (...\node_modules\json5\lib\parse.js:78:42)
ERR!     at Object.parse (...\node_modules\json5\lib\parse.js:25:17)
```

Our `.babelrc` file is proper JSON and does not have a "c" character at the beginning of the file, but our `babel.config.js` does. It appears that Storybook is either trying to parse the wrong Babel config file or is using the wrong parser.

We've never had this problem with any previous release of Storybook. Something changed in the last week or two to cause this.

**System:**
 - OS: Windows 10
 - Framework: React
 - Version: 5.1.0-rc.0

**Comment by shilman** [comment]
Yeah this was a bad change made for #6633

**Comment by ndelangen** [comment]
Thanks for reporting @kaiyoma!

**Comment by ndelangen** [comment]
related: https://github.com/storybooks/storybook/pull/6634

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-rc.2 containing PR #6878 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by kaiyoma** [comment]
Thanks, the new release fixed the config parsing issue, though we still can't upgrade because a lot of other functionality is still broken. See https://github.com/storybooks/storybook/issues/6813.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.29 containing PR #7104 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@debug` NPM tag.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-alpha.29 containing PR #7104 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@debug` NPM tag.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.9 containing PR #7104 that references this issue. Upgrade today to try it out!
